return {
    "theprimeagen/harpoon",
    event = "VeryLazy",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
        vim.keymap.set("n", "<leader>a", function()
            require("harpoon.mark").add_file()
        end)
        vim.keymap.set("n", "<A-a>", function()
            require("harpoon.ui").toggle_quick_menu()
        end)
        vim.keymap.set("n", "<A-1>", function()
            require("harpoon.ui").nav_file(1)
        end)
        vim.keymap.set("n", "<A-2>", function()
            require("harpoon.ui").nav_file(2)
        end)
        vim.keymap.set("n", "<A-3>", function()
            require("harpoon.ui").nav_file(3)
        end)
        vim.keymap.set("n", "<A-4>", function()
            require("harpoon.ui").nav_file(4)
        end)
        vim.keymap.set("n", "<A-5>", function()
            require("harpoon.ui").nav_file(5)
        end)
        vim.keymap.set("n", "<A-6>", function()
            require("harpoon.ui").nav_file(6)
        end)
        vim.keymap.set("n", "<A-7>", function()
            require("harpoon.ui").nav_file(7)
        end)
        vim.keymap.set("n", "<A-8>", function()
            require("harpoon.ui").nav_file(8)
        end)
        vim.keymap.set("n", "<A-9>", function()
            require("harpoon.ui").nav_file(9)
        end)
        vim.keymap.set("n", "<A-0>", function()
            require("harpoon.ui").nav_file(10)
        end)
    end
}

